# Generated by Django 2.2 on 2019-11-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0002_auto_20191109_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='termsAccepted',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
    ]
